/* eslint-disable no-unused-vars */
const exbrowser = "whale";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.turnoffthelights.com/browser/extension/options/";
const linkcapturescreenshot = "https://www.turnoffthelights.com/browser/extension/capture-screenshot-of-video/";
const linkdeveloperwebsite = "https://www.turnoffthelights.com";
const linkproduct = "https://store.whale.naver.com/detail/oplanocjcpankemphfllmlhglnloaolj";
const linkdonate = "https://www.turnoffthelights.com/donate/";
const writereview = "https://store.whale.naver.com/detail/oplanocjcpankemphfllmlhglnloaolj";
const linkchangelog = "https://www.turnoffthelights.com/browser/extension/changelog/whale/";
const linktranslate = "https://www.turnoffthelights.com/browser/extension/translate/";
const linksupport = "https://www.turnoffthelights.com/support/";
const linkwelcome = "https://www.turnoffthelights.com/browser/extension/welcome/whale/";
const linkuninstall = "https://www.turnoffthelights.com/browser/extension/uninstall/whale/";
const linkguide = "https://www.turnoffthelights.com/browser/extension/guide/whale/";
const linkbrowsertheme = "https://www.turnoffthelights.com/browser/theme/";
const browsernewtab = "whale://newtab/";
const browserstore = "https://store.whale.naver.com";
const linkyoutube = "https://www.youtube.com/@turnoffthelights?sub_confirmation=1";
const linkauroraplayerapp = "https://www.stefanvd.net/project/aurora-player/";
const linktotlmobileapp = "https://www.turnoffthelights.com/mobile/";
const linkgamepad = "https://www.turnoffthelights.com/game-controller/";
const devmode = true;
const devdonate = false;