/* eslint-disable no-unused-vars */
const exbrowser = "chrome";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.turnoffthelights.com/browser/extension/options/";
const linkcapturescreenshot = "https://www.turnoffthelights.com/browser/extension/capture-screenshot-of-video/";
const linkdeveloperwebsite = "https://www.turnoffthelights.com";
const linkproduct = "https://galaxystore.samsung.com/detail/com.stefanvd.turnoffthelightssamsung";
const linkdonate = "https://www.turnoffthelights.com/donate/";
const writereview = "https://galaxystore.samsung.com/detail/com.stefanvd.turnoffthelightssamsung";
const linkchangelog = "https://www.turnoffthelights.com/browser/extension/changelog/samsung/";
const linktranslate = "https://www.turnoffthelights.com/browser/extension/translate/";
const linksupport = "https://www.turnoffthelights.com/support/";
const linkwelcome = "https://www.turnoffthelights.com/browser/extension/welcome/samsung/";
const linkuninstall = "https://www.turnoffthelights.com/browser/extension/uninstall/samsung/";
const linkguide = "https://www.turnoffthelights.com/browser/extension/guide/samsung/";
const linkbrowsertheme = "https://www.turnoffthelights.com/browser/theme/";
const browsernewtab = "chrome://newtab/";
const browserstore = "https://galaxystore.samsung.com";
const linkyoutube = "https://www.youtube.com/@turnoffthelights?sub_confirmation=1";
const linkauroraplayerapp = "https://www.stefanvd.net/project/aurora-player/app/";
const linktotlmobileapp = "https://www.turnoffthelights.com/mobile/";
const linkgamepad = "https://www.turnoffthelights.com/game-controller/";
const linknightmodeapp = "https://www.turnoffthelights.com/browser/extension/night-mode/";
const devmode = true;
const devdonate = false;